// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5owHAGh5XbkLLFriFqPBX_kC4WdQYec',
    appId: '1:910761596990:web:43295d9fedcac5cb03596f',
    messagingSenderId: '910761596990',
    projectId: 'stylevault-11a65',
    authDomain: 'stylevault-11a65.firebaseapp.com',
    storageBucket: 'stylevault-11a65.firebasestorage.app',
    measurementId: 'G-H9NC7TD1WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0_SFHNGJtWcbtHBgJNmgTauwKuszdjg',
    appId: '1:910761596990:android:f51786c24f598ed503596f',
    messagingSenderId: '910761596990',
    projectId: 'stylevault-11a65',
    storageBucket: 'stylevault-11a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZb-kxIXnuV9uOfBAqBL7zE65zdRbhQQ',
    appId: '1:910761596990:ios:fe6d50d747545eac03596f',
    messagingSenderId: '910761596990',
    projectId: 'stylevault-11a65',
    storageBucket: 'stylevault-11a65.firebasestorage.app',
    iosBundleId: 'com.example.stylevault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZb-kxIXnuV9uOfBAqBL7zE65zdRbhQQ',
    appId: '1:910761596990:ios:fe6d50d747545eac03596f',
    messagingSenderId: '910761596990',
    projectId: 'stylevault-11a65',
    storageBucket: 'stylevault-11a65.firebasestorage.app',
    iosBundleId: 'com.example.stylevault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5owHAGh5XbkLLFriFqPBX_kC4WdQYec',
    appId: '1:910761596990:web:d92db1d06932b2f703596f',
    messagingSenderId: '910761596990',
    projectId: 'stylevault-11a65',
    authDomain: 'stylevault-11a65.firebaseapp.com',
    storageBucket: 'stylevault-11a65.firebasestorage.app',
    measurementId: 'G-FV0279YJH3',
  );
}
